export const SPECIES_FAMILIES: Record<string, string> = {
  "Carcharodus alceae": "Hesperiidae",
  "Carcharodus baeticus": "Hesperiidae",
  "Carcharodus tripolinus": "Hesperiidae",
  "Erynnis tages": "Hesperiidae",
  "Gegenes nostrodamus": "Hesperiidae",
  "Hesperia comma": "Hesperiidae",
  "Muschampia proto": "Hesperiidae",
  "Ochlodes sylvanus": "Hesperiidae",
  "Pyrgus alveus": "Hesperiidae",
  "Pyrgus armoricanus": "Hesperiidae",
  "Pyrgus malvoides": "Hesperiidae",
  "Pyrgus onopordi": "Hesperiidae",
  "Pyrgus serratulae": "Hesperiidae",
  "Spialia sertorius": "Hesperiidae",
  "Thymelicus acteon": "Hesperiidae",
  "Thymelicus lineola": "Hesperiidae",
  "Thymelicus sylvestris": "Hesperiidae",
  "Aricia cramera": "Lycaenidae",
  "Aricia montensis": "Lycaenidae",
  "Cacyreus marshalli": "Lycaenidae",
  "Callophrys avis": "Lycaenidae",
  "Callophrys rubi": "Lycaenidae",
  "Celastrina argiolus": "Lycaenidae",
  "Cupido lorquinii": "Lycaenidae",
  "Cupido minimus": "Lycaenidae",
  "Eumedonia eumedon": "Lycaenidae",
  "Favonius quercus": "Lycaenidae",
  "Glaucopsyche alexis": "Lycaenidae",
  "Glaucopsyche melanops": "Lycaenidae",
  "Hamearis lucina": "Lycaenidae",
  "Laeosopis roboris": "Lycaenidae",
  "Lampides boeticus": "Lycaenidae",
  "Leptotes pirithous": "Lycaenidae",
  "Lycaena alciphron": "Lycaenidae",
  "Lycaena bleusei": "Lycaenidae",
  "Lycaena phlaeas": "Lycaenidae",
  "Lycaena tityrus": "Lycaenidae",
  "Lycaena virgaureae": "Lycaenidae",
  "Lysandra bellargus": "Lycaenidae",
  "Phengaris alcon": "Lycaenidae",
  "Plebejus argus": "Lycaenidae",
  "Polyommatus icarus/celina": "Lycaenidae",
  "Polyommatus semiargus": "Lycaenidae",
  "Cyaniris semiargus": "Lycaenidae", // Synonym for Polyommatus semiargus
  "Polyommatus thersites": "Lycaenidae",
  "Pseudophilotes abencerragus": "Lycaenidae",
  "Pseudophilotes baton": "Lycaenidae",
  "Pseudophilotes panoptes": "Lycaenidae",
  "Satyrium esculi": "Lycaenidae",
  "Satyrium ilicis": "Lycaenidae",
  "Satyrium spini": "Lycaenidae",
  "Thecla betulae": "Lycaenidae",
  "Tomares ballus": "Lycaenidae",
  "Zizeeria knysna": "Lycaenidae",
  "Aglais io": "Nymphalidae",
  "Aglais urticae": "Nymphalidae",
  "Apatura ilia": "Nymphalidae",
  "Argynnis pandora": "Nymphalidae",
  "Argynnis paphia": "Nymphalidae",
  "Boloria dia": "Nymphalidae",
  "Boloria euphrosyne": "Nymphalidae",
  "Boloria selene": "Nymphalidae",
  "Brenthis daphne": "Nymphalidae",
  "Brenthis hecate": "Nymphalidae",
  "Brenthis ino": "Nymphalidae",
  "Charaxes jasius": "Nymphalidae",
  "Danaus chrysippus": "Nymphalidae",
  "Danaus plexippus": "Nymphalidae",
  "Euphydryas aurinia": "Nymphalidae",
  "Euphydryas desfontainii": "Nymphalidae",
  "Fabriciana adippe": "Nymphalidae",
  "Fabriciana niobe": "Nymphalidae",
  "Issoria lathonia": "Nymphalidae",
  "Libythea celtis": "Nymphalidae",
  "Limenitis camilla": "Nymphalidae",
  "Limenitis reducta": "Nymphalidae",
  "Melitaea aetherie": "Nymphalidae",
  "Melitaea cinxia": "Nymphalidae",
  "Melitaea deione": "Nymphalidae",
  "Melitaea didyma": "Nymphalidae",
  "Melitaea celadussa": "Nymphalidae",
  "Melitaea parthenoides": "Nymphalidae",
  "Melitaea phoebe": "Nymphalidae",
  "Melitaea trivia": "Nymphalidae",
  "Nymphalis antiopa": "Nymphalidae",
  "Nymphalis polychloros": "Nymphalidae",
  "Polygonia c-album": "Nymphalidae",
  "Speyeria aglaja": "Nymphalidae",
  "Vanessa atalanta": "Nymphalidae",
  "Vanessa cardui": "Nymphalidae",
  "Vanessa virginiensis": "Nymphalidae",
  "Iphiclides feisthamelii": "Papilionidae",
  "Papilio machaon": "Papilionidae",
  "Zerynthia rumina": "Papilionidae",
  "Anthocharis cardamines": "Pieridae",
  "Anthocharis euphenoides": "Pieridae",
  "Aporia crataegi": "Pieridae",
  "Colias crocea": "Pieridae",
  "Euchloe belemia": "Pieridae",
  "Euchloe crameri": "Pieridae",
  "Euchloe tagis": "Pieridae",
  "Gonepteryx cleopatra": "Pieridae",
  "Gonepteryx rhamni": "Pieridae",
  "Leptidea sinapis": "Pieridae",
  "Pieris brassicae": "Pieridae",
  "Pieris napi": "Pieridae",
  "Pieris rapae": "Pieridae",
  "Pontia daplidice": "Pieridae",
  "Arethusana arethusa": "Nymphalidae",
  "Brintesia circe": "Nymphalidae",
  "Coenonympha arcania": "Nymphalidae",
  "Coenonympha dorus": "Nymphalidae",
  "Coenonympha glycerion": "Nymphalidae",
  "Coenonympha pamphilus": "Nymphalidae",
  "Erebia triarius": "Nymphalidae",
  "Hipparchia fidia": "Nymphalidae",
  "Hipparchia hermione": "Nymphalidae",
  "Hipparchia semele": "Nymphalidae",
  "Hipparchia statilinus": "Nymphalidae",
  "Hyponephele lupinus": "Nymphalidae",
  "Hyponephele lycaon": "Nymphalidae",
  "Lasiommata maera": "Nymphalidae",
  "Lasiommata megera": "Nymphalidae",
  "Maniola jurtina": "Nymphalidae",
  "Melanargia ines": "Nymphalidae",
  "Melanargia lachesis": "Nymphalidae",
  "Melanargia occitanica": "Nymphalidae",
  "Melanargia russiae": "Nymphalidae",
  "Pararge aegeria": "Nymphalidae",
  "Pyronia bathseba": "Nymphalidae",
  "Pyronia cecilia": "Nymphalidae",
  "Pyronia tithonus": "Nymphalidae",
  "Satyrus actaea": "Nymphalidae",
};

export const endangered_pt: Record<string | number | symbol, string> = {
  // Diurnas
  "Pyrgus alveus": "CR",
  "Pyrgus serratulae": "EN",
  "Eumedonia eumedon": "EN",
  "Phengaris alcon": "EN",
  "Brenthis hecate": "EN",
  "Euphydryas desfontainii": "EN",
  "Lycaena virgaureae": "VU",
  "Boloria euphrosyne": "VU",
  "Brenthis ino": "VU",
  "Melitaea aetherie": "VU",
  "Euchloe tagis": "VU",
  "Hamearis lucina": "VU",

  // Noturnas
  "Idaea luteolaria": "CR",
  "Apamea scolopacina": "CR",
  "Chersotis oreina": "CR",
  "Euchalcia modestoides": "CR",
  "Hadena luteocincta": "CR",
  "Axia margarita": "EN",
  "Phragmataecia castaneae": "EN",
  "Callimorpha dominula": "EN",
  "Pelosia plumosa": "EN",
  "Setina cantabrica": "EN",
  "Cyclophora pendularia": "EN",
  "Cyclophora serveti": "EN",
  "Ekboarmia miniaria": "EN",
  "Idaea simplicior": "EN",
  "Lomographa bimaculata": "EN",
  "Scopula immorata": "EN",
  "Siona lineata": "EN",
  "Acronicta cuspis": "EN",
  "Agrotis charoae": "EN",
  "Agrotis clavis": "EN",
  "Anorthoa munda": "EN",
  "Archanara dissoluta": "EN",
  "Athetis pallustris": "EN",
  "Cucullia gnaphalii": "EN",
  "Epipsilia latens": "EN",
  "Globia sparganii": "EN",
  "Hada plebeja": "EN",
  "Lacanobia blenna": "EN",
  "Lateroligia ophiogramma": "EN",
  "Leucania comma": "EN",
  "Pachetra sagittigera": "EN",
  "Panemeria tenebrata": "EN",
  "Drymonia dodonaea": "EN",
  "Rhegmatophila alpina": "EN",

  "Catocala fraxini": "VU",
  "Charissa crenulata": "VU",
  "Idaea humiliata": "VU",
  "Zygaena nevadensis": "VU",
  "Zygaena rhadamanthus": "VU",
};

export const endangered_eu: Record<string | number | symbol, string> = {
  "Papilio alexanor": "NT",
  "Archon apollinus": "VU",
  "Zerynthia cretica": "NT",
  "Carterocephalus silvicola": "NT",
  "Carterocephalus palaemon": "NT",
  "Thymelicus sylvestris": "VU",
  "Thymelicus lineola": "VU",
  "Spialia orbifer": "NT",
  "Muschampia cribrellum": "VU",
  "Carcharodus lavatherae": "NT",
  "Carcharodus baeticus": "VU",
  "Pyrgus malvoides": "NT",
  "Pyrgus malvae": "NT",
  "Pyrgus centaureae": "VU",
  "Pyrgus onopordi": "NT",
  "Leptidea morsei": "VU",
  "Gonepteryx cleobule": "EN",
  "Gonepteryx maderensis": "EN",
  "Colias chrysotheme": "EN",
  "Colias myrmidone": "VU",
  "Colias caucasica": "VU",
  "Colias tyche": "VU",
  "Colias hecla": "VU",
  "Pontia chloridice": "EN",
  "Pieris krueperi": "NT",
  "Pieris cheiranthi": "EN",
  "Euchloe eversi": "NT",
  "Euchloe grancanariensis": "NT",
  "Euchloe penia": "NT",
  "Euchloe bazae": "EN",
  "Zegris eupheme": "NT",
  "Anthocharis damone": "EN",
  "Lycaena helle": "NT",
  "Tomares nogelii": "NT",
  "Callophrys avis": "NT",
  "Satyrium pruni": "VU",
  "Satyrium spini": "VU",
  "Cyclyrius webbianus": "NT",
  "Tarucus theophrastus": "NT",
  "Phengaris alcon": "NT",
  "Phengaris arion": "NT",
  "Phengaris teleius": "VU",
  "Phengaris nausithous": "NT",
  "Turanana taygetica": "EN",
  "Pseudophilotes barbagiae": "EN",
  "Iolana iolas": "NT",
  "Cupido minimus": "NT",
  "Agriades optilete": "VU",
  "Agriades dardanus": "EN",
  "Agriades zullichi": "EN",
  "Agriades aquilo": "EN",
  "Kretania psylorita": "NT",
  "Kretania hesperica": "NT",
  "Kretania trappi": "EN",
  "Neolysandra coelestina": "NT",
  "Lysandra bellargus": "NT",
  "Polyommatus golgus": "EN",
  "Polyommatus ripartii": "NT",
  "Polyommatus nephohiptamenos": "EN",
  "Polyommatus violetae": "EN",
  "Polyommatus fabressei": "NT",
  "Polyommatus dolus": "NT",
  "Polyommatus humedasae": "CR",
  "Polyommatus timfristos": "NT",
  "Polyommatus orphicus": "EN",
  "Boloria polaris": "EN",
  "Boloria improba": "EN",
  "Boloria frigga": "VU",
  "Boloria freija": "EN",
  "Boloria chariclea": "EN",
  "Aglais urticae": "NT",
  "Euphydryas iduna": "EN",
  "Euphydryas maturna": "VU",
  "Melitaea aetherie": "EN",
  "Melitaea britomartis": "NT",
  "Melitaea asteria": "EN",
  "Coenonympha phryne": "CR",
  "Coenonympha oedippus": "NT",
  "Coenonympha tullia": "EN",
  "Coenonympha orientalis": "NT",
  "Lopinga achine": "NT",
  "Pararge xiphia": "NT",
  "Hipparchia tilosi": "EN",
  "Hipparchia bacchus": "VU",
  "Hipparchia wyssii": "NT",
  "Hipparchia tamadabae": "VU",
  "Hipparchia miguelensis": "NT",
  "Hipparchia azorina": "NT",
  "Hipparchia leighebi": "NT",
  "Hipparchia sbordonii": "CR",
  "Hipparchia christenseni": "CR",
  "Oeneis bore": "EN",
  "Oeneis jutta": "NT",
  "Oeneis norna": "VU",
  "Chazara prieuri": "EN",
  "Pseudochazara geyeri": "EN",
  "Pseudochazara amymone": "EN",
  "Pseudochazara amalthea": "NT",
  "Pseudochazara williamsi": "CR",
  "Pseudochazara euxina": "EN",
  "Pseudochazara cingovskii": "CR",
  "Pseudochazara tisiphone": "NT",
  "Pseudochazara orestes": "EN",
  "Maniola chia": "VU",
  "Maniola halicarnassus": "NT",
  "Erebia embla": "VU",
  "Erebia disa": "EN",
  "Erebia hispania": "NT",
  "Erebia rondoui": "NT",
  "Erebia nivalis": "NT",
  "Erebia neleus": "NT",
  "Erebia sthennyo": "NT",
  "Erebia epistygne": "VU",
  "Erebia palarica": "NT",
  "Erebia gorgone": "NT",
  "Erebia rhodopensis": "NT",
  "Erebia sudetica": "EN",
  "Erebia triarius": "NT",
  "Erebia christi": "NT",
  "Erebia orientalis": "NT",
  "Erebia flavofasciata": "EN",
  "Erebia scipio": "VU",
  "Erebia melas": "NT",
  "Erebia lefebvrei": "NT",
  "Erebia zapateri": "NT",
};

export const HABITAT_TRANSLATIONS: Record<string, string> = {
  "open areas": "Áreas Abertas",
  "agricultural areas": "Áreas Agrícolas",
  meadow: "Prados",
  grassland: "Pradarias",
  "rocky areas": "Zonas Rochosas",
  gardens: "Jardins",
  "disturbed areas": "Áreas Perturbadas",
  woodland: "Zonas Florestais",
  "woodland edges": "Margens De Floresta",
  wetlands: "Zonas Húmidas",
  "woodland clearings": "Clarões De Floresta",
  parks: "Parques",
  "riparian woodland": "Florestas Ribeirinhas",
  roadsides: "Beiras De Estrada",
  "diverse habitats": "Habitats Diversos",
  "alpine meadows": "Prados Alpinos",
  hillsides: "Encostas",
  "woodland rides": "Caminhos Florestais",
  hedgerow: "Sebes",
  scrubland: "Matagais",
  heathland: "Charnecas",
  "sand dunes": "Dunas De Areia",
  "dry grassland": "Pradarias Secas",
  coastal: "Zonas Costeiras",
  "calcareous grassland": "Pradarias Calcárias",
  quarries: "Pedreiras",
  "abandoned orchards": "Pomares Abandonados",
  "dry slopes": "Encostas Secas",
  Generalist: "Generalista",
  "Rocky/Mountain": "Rochoso/Montanhoso",
  "Urban/Agricultural": "Urbano/Agrícola",
  Coastal: "Costeiro",
  Grassland: "Pradaria",
  Woodland: "Floresta",
  Scrubland: "Matagais",
  Wetland: "Zonas Húmidas",
};

export interface SpeciesEcology {
  habitats: string[];
  habitatType: string;
  hostPlantFamilies: string[];
  hostPlantSpecies: Record<string, string[]>;
  sources: string[];
}

export interface SpeciesDetails {
  rarity: "very-common" | "common" | "uncommon" | "rare";
  sizeCategory: "pequena" | "média" | "grande" | "";
  predominantColor: string | string[];
  months: string[];
  similarSpecies: {
    name: string;
    distinction: string;
  }[];
  identificationTips?: string;
}

export interface Species {
  latinName: string;
  commonName: string;
  family: string;
  ecology?: SpeciesEcology;
  details?: SpeciesDetails;
  attribution?: string;
}
